### ISSUE TITLE
event bubbling

### ISSUE THREAD

**Issue by arabeske654** [jawj/OverlappingMarkerSpiderfier#35]
Hi there,

nice job, thumbs up.
the addListener('click', function(marker){....
is bubbling on my application, how do I prevent from this?
Using this listener to load content with ajax in separate div. The listener is calling the ajax-function four times.

warm regards

**Comment by Mattabile** [comment]
I don't understand very well, (perhaps beacause I'm French) , to stop propagation of event click is not the same to stop click, so ... event.stop doesn't work for stop propagation where we are in a loop:
`        $.ajax({
            url: myUrl,
            type: 'POST',
            dataType: 'json',
        }).success(function (response) {
                   $.each(response, function (key, value) {
                        oms.addListener('click', function (marker,event) {
                                infowindow.open(map, marker);
                            });
                    })
})`

if we call many times this ajax, we have to click many times cross close infowindow . I don't find any solutions for stopPropagation. I have explorated many possibilities:
google.maps.event.clearInstanceListeners(marker); not working
google.maps.event.clearListeners(marker, 'click'); not working
I can write   oms.addListener out of loop because else I must request all markers first and they are too many !
Since 7 May 2013 , i've you got a solution ?

**Comment by Mattabile** [comment]
I find a solution ... you have implement clearListeners method ... good work !!
oms.clearListeners('click');

The solution was simple, I went to the moon ... Sorry for the inconvenience
